### PR TITLE
Update sample Makefile and add test-running helper

### LINKED ISSUE #54: improve makefile
Make the makefile example better for contests

### PR DESCRIPTION
**Pull request by ProtractorNinja**
Resolves #54.

### CODE REVIEW

**Comment by robertu94** [comment]
I am completely behind the changes to the makefile, but the testing helper script seems heavy.  Is there anything that we could do to slim this down/include it in the makefile?

**Comment by ProtractorNinja** [comment]
@robertu94 Err.. what? I don't understand how a script that takes no more than two minutes to type could be considered "heavy".

**Comment by robertu94** [comment]
I just feel like there is 2 line solution to this that could be included in the makefile without an external script.

**Comment by ProtractorNinja** [comment]
I don't think so -- I found out during the last ICPC that trying to merge versatile testing code with build rules is a bad idea, because my short and dirty solution ended up mucking up my workflow down the line. Externalizing that bit has some advantages:

- It's clean -- the Makefile's only job is to build, and the script's is to test.
   - The script doesn't need to worry about Make's stupid syntax problems (just Bash's).
   - Make won't get tripped up with unchanging text file dependencies anywhere or scripting syntax.
   - I don't think Make can call a common testing rule from multiple places, anyway.
- The script's output tells you what's going on without you needing to think about it, unlike something shorter like `diff`'s:
```
>> ./t echo
g++ echo.cpp -g -Wall -o echo
>> running with echo.a.in
55
>> running with echo.b.in (output differs)
66
--- doesn't match echo.b.out: ---
9999
```

Emphasizing shortness just for shortness' sake doesn't make any sense here. There's no reason to prefer a short, barely functional setup over one that offers clarity and ease-of-use for the low price of an extra minute or two.

**Pull request merged**
